database:
  path: data/database/ikuyo.db
  wal_mode: true
  read_pool:
    size: 5
    timeout: 30
    health_check_interval: 300
  write_connection:
    timeout: 60
    pragma_settings:
      - "PRAGMA journal_mode=WAL"
      - "PRAGMA synchronous=NORMAL"
      - "PRAGMA cache_size=10000"

site:
  base_url: https://mikanani.me
  allowed_domains:
    - mikanani.me
  start_urls:
    - https://mikanani.me/Home

crawler:
  download_delay: 0.2
  concurrent_requests: 16
  concurrent_requests_per_domain: 12
  retry_times: 3
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

scheduler:
  enabled: true
  default_cron: "0 2 * * *"
  timezone: Asia/Shanghai
  jobs:
    - id: mikan_crawler
      name: Mikan爬虫定时任务
      cron: "0 2 * * *"
      enabled: true
      description: 定时爬取Mikan Project动画资源
      mode: homepage
  scheduler_settings:
    job_defaults:
      coalesce: false
      max_instances: 1
      misfire_grace_time: 300

output:
  output_dir: output

bangumi:
  base_url: https://api.bgm.tv
  timeout: 10
  user_agent: "IKuYo/2.0.0"

# 缓存配置
cache:
  # TTL配置（秒）- 基于数据特性优化
  ttl:
    calendar: 14400    # 每日放送：4小时（相对稳定）
    subject: 7200      # 番剧详情：2小时（评分变化较频繁）
    episodes: 3600     # 章节信息：1小时（新章节更新）
    default: 1800      # 默认：30分钟

  # 内存缓存限制
  memory_limits:
    calendar: 10      # 每日放送缓存数量
    subject: 1000     # 番剧详情缓存数量
    episodes: 500     # 章节信息缓存数量
    default: 100      # 默认缓存数量

  # 持久化策略
  persist_types: ["calendar", "subject", "episodes"]  # 持久化每日放送、番剧详情、章节信息

  # 清理策略
  cleanup_on_startup: true     # 启动时清理过期文件
