[project]
name = "ikuyo"
version = "0.1.0"
description = "动画爬虫，获取种子资源"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.0",
    "beautifulsoup4>=4.13.4",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "scrapy>=2.13.2",
]
